### PR TITLE
Add from2-array to a See Also section

### PR DESCRIPTION
**Pull request by bcomnes**
Found out about from2 and from2-array today.  This would make from2-array a little more discoverable, and was inspired by github.com/rvagg/through2#see-also.  Are there any other known from2 wrappers that should also be added?

Just wondering, is there a to2 that is a similar Convince wrapper for writable streams?

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
neat! `from2-string` is probably worth mentioning too https://github.com/yoshuawuyts/from2-string

**Comment by mafintosh** [comment]
@yoshuawuyts send a pr :)

**Comment by mafintosh** [comment]
@bcomnes i've been using this for purely writeable streams, https://github.com/mafintosh/flush-write-stream

**Comment by bcomnes** [comment]
from2-string looks great!  I'll pr it toady unless someone beats me to it.  

Flush-write looks perfect :+1:

**Pull request merged**
